font_family CaskaydiaCove Nerd Font
font_family Cascadia Code
font_family Cascadia Code Nerd Font
font_family Cascadia Code Nerd Font

font_size 12
background_opacity 1
confirm_os_window_close 0


# BEGIN_KITTY_THEME
# Cyberpunk
include current-theme.conf
# END_KITTY_THEME

# Aliases
alias upd='sudo dnf update'
