# ==============================================================================
# H Y P R L A N D   M A S T E R   C O N F I G - T490 DEV HUB
# ==============================================================================

# 1. VARIÁVEIS GLOBAIS DE SISTEMA (Precisam ser lidas antes de tudo para que os atalhos funcionem)
$mainMod = SUPER

# 2. IMPORTAÇÃO DOS MÓDULOS (SOURCING)
source = ~/.config/hypr/hypr-system.conf
source = ~/.config/hypr/hypr-visuals.conf
source = ~/.config/hypr/hypr-inputs.conf
