# <https://wiki.hypr.land/Hypr-Ecosystem/hypridle/>
general {
	lock_cmd = pidof hyprlock || hyprlock                       # evita que multiplas instâncias do hyprlock sejam abertas
	before_sleep_cmd = loginctl lock-session                    # bloqueia antes de suspender
	after_sleep_cmd = hyprctl dispatch dpms on                  # evita que precise apertar uma tecla duas vezes para ligar o display
}

listener {
	timeout = 120                                               ### 2 min
	on-timeout = brightnessctl -s set 25                        # controla a backlight do monitor
	on-resume = brightnessctl -r                                # restaura a backlight ao padrão
}

listener {
	timeout = 300                                               ### 5 min
	on-timeout = loginctl lock-session                          # bloqueia a tela no timeout (5 min)
}

listener {
	timeout = 330                                               ### 5,5 min
	on-timeout = hyprctl dispatch dpms off                      # desliga a tela passado o timeout
	on-resume = hyperctl dispatch dpms on && brightnessctl -r   # liga a tela após detectar atividade depois do timeout
}

listener {
	timeout = 1800                                              ### 30 min
	on-timeout = systemctl suspend                              # suspende o sistema após 30 minutos
}
