# P R O G R A M S
### https://wiki.hypr.land/Configuring/Keywords/
$terminal = kitty   # Terminal padrão
$fileManager = dolphin   # File Manager padrão
$menu = rofi -show drun   # App Launcher padrão


# A U T O S T A R T
exec-once = waybar & hyprpaper & firefox
exec-once = nm-applet --indicator
exec-once = blueman-applet
exec-once = /usr/libexec/kf6/polkit-kde-authentication-agent-1
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store
exec-once = [workspace special:scratchpad silent] kitty --class scratchpad -e micro
exec-once = ibus-daemon -rxRd



# E N V I R O N M E N T   V A R I A B L E S
### https://wiki.hypr.land/Configuring/Environment-variables/
env = XCURSOR_SIZE,24
env = HYPRCURSOR_SIZE,24
env = MOZ_ENABLE_WAYLAND,1
env = GTK_IM_MODULE,ibus
env = QT_IM_MODULE,ibus
env = XMODIFIERS,@im=ibus



# P E R M I S S I O N S
### https://wiki.hypr.land/Configuring/Permissions/
# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
