preload = ~/Pictures/wallpapers/battlegear.jpg
wallpaper = HDMI-A-2, ~/Pictures/wallpapers/battlegear.jpg
splash = false

#wallpaper {
#	monitor = 
#    	path = ~/battlegear.jpg
#    	fit_mode = cover
#}
